### ISSUE TITLE
Corrupted Worlds using Docker for Desktop on Windows 11

### ISSUE THREAD

**Issue by gustaavik** [sVoxelDev/minecraft-server-template#7]
I just started the server, all the docker containers are running just fine. As soon as the world started to load I began getting the following error. I am not getting it when I just open a normal simple server.
https://pastebin.com/0wLePEDT

**Comment by gustaavik** [comment]
When that is said, I am unable to find the `/data` directory, so the problem might have something to do with it not existing

**Comment by Silthus** [comment]
Could it be that you are running Windows 11 and Docker for Windows?
There seems to be a known issue with Windows 11 and corrupted worlds. See this issue here: https://github.com/itzg/docker-minecraft-server/issues/1247

Btw. I am having the same problem on my Windows 11 PC. On Windows 10 everything still works fine.
